codecov:
  branch: main
comment:
  behavior: default
  require_changes: true
coverage:
  range: 10..95
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 10.0
        threshold: 0.1
    patch:
      default:
        branches: null
